SHOP_NAME = "Lucy Bakery"
OWNER_EMAIL_PRIMARY = "minseobong0@gmail.com"
WELCOME_COUPON_AMOUNT = "2000"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "465"
SMTP_USER = "minseobong0@gmail.com"
SMTP_PASS = "qynbscwxhothodoj"
