[gcp_service_account]
type = "service_account"
project_id = "aimenuapp-474706"
private_key_id = "...."
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = "lucy-bakery-sa@aimenuapp-474706.iam.gserviceaccount.com"
client_id = "...."
token_uri = "https://oauth2.googleapis.com/token"

GSPREAD_SPREADSHEET = "LucyDB"
GSPREAD_CUSTOMER_SHEET = "customers"
GSPREAD_ORDER_SHEET = "orders"

SHOP_NAME = "Lucy Bakery"
OWNER_EMAIL_PRIMARY = "minseobong0@gmail.com"
WELCOME_COUPON_AMOUNT = "2000"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "465"
SMTP_USER = "minseobong0@gmail.com"
SMTP_PASS = "qynbscwxhothodoj"
